# Generated by Django 5.1 on 2024-09-17 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductEntry',
        ),
    ]
